### PR TITLE
jaxlib 0.4.25 :snowflake:

### PR DESCRIPTION
**Pull request by Andrii-Osipov**
jaxlib 0.4.25 :snowflake:

**Destination channel:** Snowflake

- [PKG-6144](https://anaconda.atlassian.net/browse/PKG-6144) 
- [Upstream repository](https://github.com/jax-ml/jax/tree/jaxlib-v0.4.25)
- [PyPi](https://pypi.org/project/jaxlib/0.4.25/)
- [conda-forge](https://github.com/conda-forge/jaxlib-feedstock/)

[PKG-6144]: https://anaconda.atlassian.net/browse/PKG-6144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cbouss** [comment]
There is a PR opened for 0.4.35 https://github.com/AnacondaRecipes/jaxlib-feedstock/pull/9 which is compatible with numpypro. We should just focus on this instead.

**Comment by Andrii-Osipov** [comment]
> There is a PR opened for 0.4.35 #9 which is compatible with numpypro. We should just focus on this instead.

https://anaconda.atlassian.net/browse/PKG-5831?focusedCommentId=248749

**Comment by cbouss** [comment]
There is a PR already approved. I don't see why we are building 0.4.25 here. Have you asked if it was okay to merge the other PR instead?

**Comment by Andrii-Osipov** [comment]
> There is a PR already approved. I don't see why we are building 0.4.25 here. Have you asked if it was okay to merge the other PR instead?
@cbouss 
Yeap, you can merge your changes, but first, add changes to the stage channel. I will check all the other stuff.

**Comment by Andrii-Osipov** [comment]
0.4.35 is finished

**Pull request closed without merging**
